card_source_all = [
{win: "gagner"},
{play: "jouer"},
{ask: "demander"},
{give: "donner"},
{carry_or_wear: "portir"},
{stamp: "timbrer"},
{ring: "sonner"},
{draw: "dessiner"},
{sharpen: "tailler"},
{lend: "prêter"},
{borrow: "emprunter"},
{eat_lunch: "déjeuner"},
{eat_dinner: "diner"},
{thank: "remercier"},
{introduce: "présenter"},
{cross_a_room: "traverser"},
{keep: "garder"},
{fold: "plier"},
{vote: "voter"},
{practice: "pratiquer"},
{leave: "quitter"},
{glue: "coller"},
{tape: "quiper"},
{distribute: "distribuer"},
{underline: "souligner"},
{search: "rechercher"},
{type: "taper"},
{surf_the_internet: "naviguer sur"},
{cut: "couper"},
{record: "enregistrer"},
{erase: "effacer"},
{think: "penser"},
{scold: "gronder"},
{trick_or_cheat: "tricher"},
{tease: "taquiner"},
{spoil: "gâter"},
{miss: "manquer"},
{last: "durer"},
{dream: "rêver"},
{fly_or_steal: "voler"},
{hide: "caher"},
# {return: "retourner"}, # There are two of these!
{fill: "remplir"},
{empty: "vider"},
{revise: "réviser"},
{suggest: "proposer"},
{spend: "dépenser"},
{waste: "gaspiller"},
{rent: "louer"},
{divide: "deviser"},
{multiply: "multiplier"},
{add: "ajouter"},
{subtract: "soustraire"},
{wish: "souhaiter"},
{discuss: "discuter"},
{study: "étudier"},
{teach: "écouter"},
{forget: "oublier"},
{listen_to: "écouter"},
{help: "aider"},
{explain: "expliquer"},
{use: "utiliser"},
{attend: "assiter"},
{accept: "accepter"},
{appreciate: "apprécier"},
{identify: "identifier"},
{admire: "admirer"},
{hiccup: "hoqueter"},
{sneeze: "éternuer"},
{cough: "tousser"},
{swallow: "avaler"},
{taste: "goûter"},
{avoid: "éviter"},
{require: "éxiger"},
{psuh: "appuyer"},
{light: "allumer"},
{correct: "corriger"},
{share: "partager"},
{repeat: "répéter"},
{prefer: "préférer"},
{buy: "acheter"},
{spell: "épeler"},
{pay: "payer"},
{cross_out: "rayer"},
{send: "envoyer"},
{finish: "finir"},
{choose: "choisir"},
{succeed: "réussir"},
{reflect: "réfléchir"},
{sell: "vendre"},
{lose: "perdre"},
{beat: "battre"},
{wait_for: "attendre"},
{hear: "entendre"},
{turn_off: "éteindre"},
{be: "être"},
{have: "avoir"},
{go: "aller"},
{come: "venir"},
{do_or_make: "faire"},
{re_do_or_do_over: "refaire"},
{be_able_to: "pouvoir"},
{want_or_wish: "vouloir"},
{have_to_or_must: "devoir"},
{say_or_tell: "dire"},
{see: "voir"},
{know_a_fact: "savoir"},
{know_be_familiar_with: "connaître"},
{read: "lire"},
{write: "écrire"},
{laugh: "rire"},
{smile: "sourire"},
{describe: "décrire"},
{sleep: "dormir"},
{take: "prendre"},
{learn: "apprendre"},
{understand: "comprendre"},
{drive: "conduire"},
{translate: "traduire"},
{stay: "rester"}, 
{fall: "tomber"},
{go_down: "descendre"},
{go_up: "monter"},
{become: "devenir"},
{return: "retourner"},
{pass_or_spend: "passer"},
{enter: "entrer"},
{re_enter: "rentrer"},
{exit: "sortir"},
{be_born: "naître"},
{die: "mourir"},
{leave_or_part: "partir"},
{come_back: "revenir"},
{snow: "neiger"},
{rain: "pleuvoir"},
{hail: "grêler"},
{stop: "arrêter"},
{wake_up: "se réveiller"},
{get_up: "se lever"},
{brush: "se brosser"},
{wash: "se laver"},
{comb: "se peigner"},
{take_a_bath: "se baigner"},
{shower: "se doucher"},
{dry: "se sêcher"},
{make_up: "se maquiller"},
{go_to_bed: "se coucher"},
{fall_asleep: "s'endormir"},
{take_a_walk: "se promener"},
{shave: "se raser"},
# Needs to have... all 150. currently contains 91-150
]
card_source_1_30 = [
{win: "gagner"},
{play: "jouer"},
{ask: "demander"},
{give: "donner"},
{carry_or_wear: "portir"},
{stamp: "timbrer"},
{ring: "sonner"},
{draw: "dessiner"},
{sharpen: "tailler"},
{lend: "prêter"},
{borrow: "emprunter"},
{eat_lunch: "déjeuner"},
{eat_dinner: "diner"},
{thank: "remercier"},
{introduce: "présenter"},
{cross_a_room: "traverser"},
{keep: "garder"},
{fold: "plier"},
{vote: "voter"},
{practice: "pratiquer"},
{leave: "quitter"},
{glue: "coller"},
{tape: "quiper"},
{distribute: "distribuer"},
{underline: "souligner"},
{search: "rechercher"},
{type: "taper"},
{surf_the_internet: "naviguer sur"},
{cut: "couper"},
{record: "enregistrer"},
]
card_source_31_60 = [
{erase: "effacer"},
{think: "penser"},
{scold: "gronder"},
{trick_or_cheat: "tricher"},
{tease: "taquiner"},
{spoil: "gâter"},
{miss: "manquer"},
{last: "durer"},
{dream: "rêver"},
{fly_or_steal: "voler"},
{hide: "caher"},
{return: "retourner"},
{fill: "remplir"},
{empty: "vider"},
{revise: "réviser"},
{suggest: "proposer"},
{spend: "dépenser"},
{waste: "gaspiller"},
{rent: "louer"},
{divide: "deviser"},
{multiply: "multiplier"},
{add: "ajouter"},
{subtract: "soustraire"},
{wish: "souhaiter"},
{discuss: "discuter"},
{study: "étudier"},
{teach: "écouter"},
{forget: "oublier"},
{listen_to: "écouter"},
{help: "aider"},
]
card_source_61_90 = [
{explain: "expliquer"},
{use: "utiliser"},
{attend: "assiter"},
{accept: "accepter"},
{appreciate: "apprécier"},
{identify: "identifier"},
{admire: "admirer"},
{hiccup: "hoqueter"},
{sneeze: "éternuer"},
{cough: "tousser"},
{swallow: "avaler"},
{taste: "goûter"},
{avoid: "éviter"},
{require: "éxiger"},
{psuh: "appuyer"},
{light: "allumer"},
{correct: "corriger"},
{share: "partager"},
{repeat: "répéter"},
{prefer: "préférer"},
{buy: "acheter"},
{spell: "épeler"},
{pay: "payer"},
{cross_out: "rayer"},
{send: "envoyer"},
{finish: "finir"},
{choose: "choisir"},
{succeed: "réussir"},
{reflect: "réfléchir"},
{sell: "vendre"},
]
card_source_91_120 = [
{lose: "perdre"},
{beat: "battre"},
{wait_for: "attendre"},
{hear: "entendre"},
{turn_off: "éteindre"},
{be: "être"},
{have: "avoir"},
{go: "aller"},
{come: "venir"},
{do_or_make: "faire"},
{re_do_or_do_over: "refaire"},
{be_able_to: "pouvoir"},
{want_or_wish: "vouloir"},
{have_to_or_must: "devoir"},
{say_or_tell: "dire"},
{see: "voir"},
{know_a_fact: "savoir"},
{know_be_familiar_with: "connaître"},
{read: "lire"},
{write: "écrire"},
{laugh: "rire"},
{smile: "sourire"},
{describe: "décrire"},
{sleep: "dormir"},
{take: "prendre"},
{learn: "apprendre"},
{understand: "comprendre"},
{drive: "conduire"},
{translate: "traduire"},
{stay: "rester"},
]
card_source_121_150 = [
{fall: "tomber"},
{go_down: "descendre"},
{go_up: "monter"},
{become: "devenir"},
{return: "retourner"},
{pass_or_spend: "passer"},
{enter: "entrer"},
{re_enter: "rentrer"},
{exit: "sortir"},
{be_born: "naître"},
{die: "mourir"},
{leave_or_part: "partir"},
{come_back: "revenir"},
{snow: "neiger"},
{rain: "pleuvoir"},
{hail: "grêler"},
{stop: "arrêter"},
{wake_up: "se réveiller"},
{get_up: "se lever"},
{brush: "se brosser"},
{wash: "se laver"},
{comb: "se peigner"},
{take_a_bath: "se baigner"},
{shower: "se doucher"},
{dry: "se sêcher"},
{make_up: "se maquiller"},
{go_to_bed: "se coucher"},
{fall_asleep: "s'endormir"},
{take_a_walk: "se promener"},
{shave: "se raser"},
]
test_array = [
{rain: "pleuvoir"},
{exit: "sortir"},
]